version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - net-postgres
      
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'foo@bar.xyz'
      PGADMIN_DEFAULT_PASSWORD: '123'
    ports:
      - "8000:80"
    deploy:
      replicas: 5
    depends_on:
      - db
    networks:
      - net-postgres

volumes:
  db-data:

networks: 
  net-postgres:
    driver: overlay
