version: '3.7'

services:
  web:
    image: nginx
    deploy:
      placement:
        constraints:
        - node.labels.loc == Narnia
      replicas: 7
      resources:
        limits:
          cpus: '0.3'
          memory: 64M
      restart_policy:
        condition: on-failure
    ports:
    - '8000:8080'
    networks:
    - net_ws


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - '8080:8080'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - net_ws

networks:
  net_ws:
    driver: overlay
