version: '3.7'
services:
  web:
    image: nginx
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: '0.7'
          memory: 64M
      restart_policy:
        condition: on-failure
    ports:
      - '8000:80'
    networks:
      - net_ws

networks:
  net_ws:             
