version: '3.7'
services:

  # https://hub.docker.com/_/odoo
  web:
    image: odoo:13
    depends_on:
      - db
    ports:
      - '8069:8069'
    environment:
      - HOST=db
      - USER=user_odoo
      - PASSWORD=123
    volumes:
      - odoo-web-data:/var/lib/odoo
  
  # https://hub.docker.com/_/postgres 
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user_odoo
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
